import { ImgRef } from "@customTypes/types"

export const imageList: ImgRef[] = [
  {
    src: "1",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title 1",
    description: " Description",
  },
  {
    src: "2",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title 2",
    description: " Description",
  },
  {
    src: "3",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title 3",
    description: " Description",
  },
  {
    src: "4",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title 4",
    description: " Description",
  },
  {
    src: "5",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title 5",
    description: " Description",
  },
  {
    src: "6",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title 6",
    description: " Description",
  },
  {
    src: "7",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title 7",
    description: " Description",
  },
  {
    src: "8",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title 8",
    description: " Description",
  },

  {
    src: "9",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title 10",
    description: " Description",
  },
  {
    src: "10",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title 11",
    description: " Description",
  },
  {
    src: "11",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title 12",
    description: " Description",
  },
  {
    src: "12",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title 13",
    description: " Description",
  },
  {
    src: "13",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title 14",
    description: " Description",
  },
  {
    src: "14",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title",
    description: "Description",
  },
  {
    src: "15",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title",
    description: "Description",
  },
  {
    src: "16",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title",
    description: "Description",
  },
  {
    src: "17",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title",
    description: "Description",
  },
  {
    src: "18",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title",
    description: "Description",
  },
  {
    src: "19",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title",
    description: "Description",
  },
  {
    src: "20",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title",
    description: "Description",
  },
  {
    src: "21",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title",
    description: "Description",
  },
  {
    src: "22",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title",
    description: "Description",
  },
  {
    src: "23",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title",
    description: "Description",
  },
  {
    src: "24",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title",
    description: "Description",
  },
  {
    src: "25",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title",
    description: "Description",
  },
  {
    src: "26",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title",
    description: "Description",
  },
  {
    src: "27",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title",
    description: "Description",
  },
  {
    src: "28",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title",
    description: "Description",
  },
  {
    src: "29",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title",
    description: "Description",
  },
  {
    src: "30",
    type: "jpg",
    alt: "ALT_TEXT_HERE",
    title: "Title",
    description: "Description",
  },
]
